server:
  port: 8081

spring:
  application:
    name: ms.login.screm
  datasource:
    url: jdbc:mysql://localhost/service_orchestrator
    username: root
    password: admin15
  jpa:
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret-password: ${JWT_TOKEN:1234343}

